### ISSUE TITLE
setup Amazon S3 storage

### ISSUE THREAD

**Issue by rosabraatz** [mammooc/mammooc.org#108]
As a developer I want to have an external storage for pictures.
- [x] get infos about how to use Amazon S3 storage
- [x] setup S3 storage
- [x] set the RRS option?
- [x] IAM user access keys via Identity and Access Management 
- [x] generate access key
- [x] use the ruby aws sdk: https://github.com/aws/aws-sdk-ruby 
- [x] set enviroment variables on heroku
- [x] relocate class amazon_s3
- [x] concept for upload provider logos
- [x] think about caching?
- [x] stub AmazonS3 instance for tests

Ref: #106, #107, #98, #96
