### ISSUE TITLE
style course detail page

### ISSUE THREAD

**Issue by mandyklingbeil** [mammooc/mammooc.org#202]
- [x] style header with course image
- [ ] #94 bookmark symbol
- [x] #93 course description
- [x] style sidebar in general, including the new Tracks
- [x] #277 only show if course was recommended or obligatory on sidebar
- [x] #321 add pagination for recommendations (still need styling)

as getting into this stuff, also doing:
- [x] #320 exclude own recommendations from lists (dashboard, course detail page)
- [x] #316 recommendations show up multiple times
- [x] #297 set max length for authors on course overview page

on extra branch now:
- #264 style recommendations

Please do not delete branch until all tasks are done.
